### ISSUE TITLE
Love this!

### ISSUE THREAD

**Issue by Sossa-DOK** [Snomaskin/ATP-Winner-Predictor#1]
Hey mate, I'm doing almost the exact same project at the moment as a beginner.

Your code is a lot better than mine in terms of the web scraping - I'm just diving into this topic.

I'm going to follow this project and if I ever catch up to your level of coding then I'll try to contribute! Good luck with it!

**Comment by Snomaskin** [comment]
Hey. Sorry for not answering sooner. I did not see your comment until now. 

It's a good project to start with and totally doable as a beginner. You get to work with tools for data gathering and then make something cool with the data too. And once you have the backend setup with an API you can build the frontend with Javascript, which is what I'm doing now. I find learning Javascript is much easier now that I have the programming fundamentals from Python. You just have to give it time and do some coding every day to improve. 

I spent way too much time on that scraper though. It was a real pain to make it work since I did not have the deep knowledge of webpage structure (DOMs) since I started learning Python with no prior programming experience. Scrapers like to work with static webpages and most modern webpages use dynamic content with Javascript. I would advice you to learn some Javascript if you want to do web scraping fo real. I wish I had started with Javascript sooner. 

Good luck to you as well and let me know if you have any questions :-)
